# Generated by Django 2.0.1 on 2018-01-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='message',
        ),
    ]
