# Generated by Django 2.0.1 on 2018-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180113_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
